name: bomiora_app
description: 보미오라 다이어트 쇼핑몰 Flutter 앱

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI 관련
  # carousel_slider: ^4.2.1  # Flutter와 충돌로 주석 처리
  
  # 네트워킹
  http: ^1.1.0
  
  # 유틸리티
  intl: ^0.20.2
  
  # 국제화 지원
  flutter_localizations:
    sdk: flutter
  
  # 상태관리 (필요시)
  # provider: ^6.1.1  # 현재 사용하지 않음
  
  # 로컬 저장소
  shared_preferences: ^2.2.2
  
  # 로컬 데이터베이스
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  path: ^1.8.3  # 현재 사용하지 않음
  
  # 이미지 캐싱
  # cached_network_image: ^3.3.0  # 현재 사용하지 않음
  
  # WebView (결제 페이지용) - 웹에서는 사용 불가
  # webview_flutter: ^4.4.2
  
  # 웹용 URL 런처
  url_launcher: ^6.2.1
  
  # URL 런처
  # url_launcher: ^6.2.1  # 현재 사용하지 않음

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # 한국어 로케일 지원
  generate: true

  # fonts:
  #   - family: NotoSans
  #     fonts:
  #       - asset: assets/fonts/NotoSansKR-Regular.ttf
  #       - asset: assets/fonts/NotoSansKR-Bold.ttf
  #         weight: 700
